[profile.default]
src = "contracts"
test = "test/solidity"
out = "forge-out"
libs = ["node_modules"]

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=node_modules/forge-std/src/",
    "@uniswap/v4-core/=node_modules/@uniswap/v4-core/",
    "@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/",
]

evm_version = "cancun"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
