[profile.default]
src = "contracts"
test = "test/solidity"
out = "forge-out"
libs = ["node_modules"]

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=node_modules/forge-std/src/",
]

evm_version = "shanghai"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
